### ISSUE TITLE
IntelOwl - job kill

### ISSUE THREAD

**Issue by WhiteHatMR** [intelowlproject/IntelOwl#213]
Hello,

I have few questions to you after some tests which I did in the IntelOwl.

I started a job - analyze the file (small one) using just VT 3.0. Then I cut the Internet to see what will happen. IntelOwl did not inform me about any job failure and process was ongoing. What more it was ongoing all the time and after 1.5h it was still in progress (I opened web gui right now and still see in progress):

1. Is it possible to end job somehow? I did not see any button on the web gui. Should it be done via CLI? If yes, is there some command for it?
2. What could be the reason that this process is going so long? I decided to check some other tools like for example Cortex and I got an output in 8min using same settings.

I will be grateful for help from your side whenever you will have time for this. Thanks in advance.

Best regards

**Comment by mlodic** [comment]
Hi, thank you for your interest in the project.

It is a strange behavior because all VirusTotal jobs have a limit configured to `500` seconds. If reached, the analyzer would fail and the interface should show the failed result. It could be something related to the front-end.

Could you please tell me which is the exact name of the analyzer? This info could be helpful because there are different analyzers for VirusTotal.

Also, could you export the logs of the application? They should be at `/var/lib/docker/volumes/intelowl_generic_logs/data/django`
Otherwise that behavior seems difficult to be replicated and to debug.
If you prefer, you can send those log to me privately instead of pasting them here.

**Comment by WhiteHatMR** [comment]
Hi,

Thanks for fast reply.
I have two VMs - one with Ubuntu 18 and there are two still ongoing jobs - already 3 days. This is why I asked how can I kill the job. On the second one Ubuntu 20 I have one still ongoing job - also cannot kill it. Actually it is done now, hmm.
Yesterday, when I was doing test on Ubuntu I was waiting 1.5h and there was still: In progress. Today I see that there is time: 93sec. I was only using VirusTotal_v3_Scan_File.
Of course, I can send you all logs. How can I do this? Maybe you will know what happened and why.

So far it looks really nice - I want to still test it and if any help will be possible, I will be really grateful.

May I also send you with that file few more questions? 

Warm regards

**Comment by Eshaan7** [comment]
> all VirusTotal jobs have a limit configured to 500 seconds.

True, but that's the soft time limit for celery task, in certain cases it may not be followed. We could also set the celery's global settings variable for hard time limit i.e. `CELERYD_TIME_LIMIT` to about 15-30 minutes. 

>  there are two still ongoing jobs - already 3 days. 
By doing the above, we should not see mishaps like this because the `check_stuck_analysis` should take care of it.

**Comment by mlodic** [comment]
> *From celery's docs,
> 
> > "The time limit is set in two values, soft and hard. The soft time limit allows the task to catch an exception to clean up before it is killed: the hard timeout isn’t catch-able and force terminates the task"

In the `docker-compose.yml` file celery is executed with the parameter `--time-limit=10000`. This is the `hard` limit: so even if something could skip the soft limit, this should kill the blocked task. I think that, by checking the logs, we can find pretty easily what is the real cause.

@WhiteHatMR you could also try to restart the containers: `docker-compose down && docker-compose up -d`, login again into the app and tell us if you see the jobs still going. By restarting the containers, everything is stopped and no jobs should be working. 

However @WhiteHatMR you can also DM directly on Twitter if you want to share logs or other details: https://twitter.com/matte_lodi

**Comment by WhiteHatMR** [comment]
Hello,

I used this command but still see those jobs running. I will reinstall whole system. Not sure what happend and why. 
I will start new tests in the new vm.

I am attaching logs and also print screen showing that jobs are running.

Best regards


![InProgress](https://user-images.githubusercontent.com/72615442/95783934-26971380-0cd3-11eb-969f-b17228b827f4.PNG)
[api_app.log](https://github.com/intelowlproject/IntelOwl/files/5367152/api_app.log)
[api_app_errors.log](https://github.com/intelowlproject/IntelOwl/files/5367153/api_app_errors.log)
[celery.log](https://github.com/intelowlproject/IntelOwl/files/5367154/celery.log)
[celery_errors.log](https://github.com/intelowlproject/IntelOwl/files/5367155/celery_errors.log)

**Comment by mlodic** [comment]
Thank you for all this info to debug the issue. I noticed this:
```
2020-10-12 19:30:01 - api_app.crons - check_stuck_analysis - ERROR - found stuck analysis, job_id:7.Setting the job to status to 'failed'
2020-10-12 19:30:01 - api_app.script_analyzers.utils - set_job_status - ERROR - setting job_id 7 to status failed
2020-10-12 19:30:02 - api_app.crons - check_stuck_analysis - ERROR - found stuck analysis, job_id:8.Setting the job to status to 'failed'
2020-10-12 19:30:02 - api_app.script_analyzers.utils - set_job_status - ERROR - setting job_id 8 to status failed
```
This is the periodic script @Eshaan7 mentioned that cleans up the blocked jobs. I think that if you click the left button that you see in the following image (you find it in the jobs table you pasted before), you will see that these jobs failed. The job result is not synced in the jobs table automatically. Otherwise, it should be synced automatically in the specific job page.
![Screenshot from 2020-10-13 16-00-08](https://user-images.githubusercontent.com/30625432/95870821-3bc08080-0d6d-11eb-8c6c-edf634db6bc3.png)

Also I noticed this:
```
['VirusTotal_v2_Get_File', 'VirusTotal_v2_Scan_File', 'VirusTotal_v3_Get_File', 'VirusTotal_v3_Get_File_And_Rescan_If_Old', 'VirusTotal_v3_Get_File_And_Scan', 'VirusTotal_v3_Get_File_And_Scan_Or_Rescan_If_Old', 'VirusTotal_v3_Scan_File']
```
These analyzers are not meant to be executed together: you should choose the most appropriate to your needs and run only one of it. If you were using a free API key, it is highly probable that VT received similar and different requests at the same time that could have blocked or stalled the process. In most cases, the one that you would like to execute is `VirusTotal_v3_Get_File_And_Scan` that would check if a file is already available in VT and, if not, would send it for a scan.

**Comment by WhiteHatMR** [comment]
Thank you very much for explanation.

I'm just trying to use different options to see how the tool will behaviour. 
I always prefer to do some unexpected actions to see how the program will react. During such actions sometimes it is possible to find something what can be improved/added/change. 
In this case it would be nice to have a button - kill job or stop job. I like this tool and this is why I want to spend on it more time doing some tests. I'm sorry if I am using it not in the proper way.
Next topic which I want to try after all tests is to check the integration with MISP. This is what I am using.
I also touched with @Eshaan7  following case:

What connections does it require from both sides:
- SIEM/SOAR <--> IntelOwl
- IntelOwl <--> TIPs?

I'm really grateful for your help, advices and all tips which you already gave to me

**Comment by Eshaan7** [comment]
We really do appreciate your inputs and efforts, @WhiteHatMR. We are open to all kinds of help, may it be code contribution or bug reports. Regarding what we have discussed here, there are two possible features/changes we can add:
#224 - We will drop the various flavors (one would still be able to configure the analyzer while requesting scan)
#225 - A button to kill an ongoing job.

**Comment by mlodic** [comment]
IntelOwl is built to be easily integrated with external platforms and other security-related tools.

By Default, IntelOwl exposes some simple APIs that can be easily leveraged with the official [client](https://github.com/intelowlproject/pyintelowl) written in Python.

So, it is required some little code to be added to the side of the tool to be integrated to properly manage this data.

For example, we have already opened an issue for the MISP: #12

**Comment by WhiteHatMR** [comment]
I think that we can close this issue as there are those two opened by @Eshaan7 
Thanks for all your help. 
I will go back to the IntelOwl study and if something will occure I will let you know.
